"""Agregar campos de firma al modelo CRT

Revision ID: d518265a1a9a
Revises: 
Create Date: 2025-09-02 12:20:36.931485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd518265a1a9a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('firma_remitente', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('firma_transportador', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('firma_destinatario', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crts', schema=None) as batch_op:
        batch_op.drop_column('firma_destinatario')
        batch_op.drop_column('firma_transportador')
        batch_op.drop_column('firma_remitente')

    # ### end Alembic commands ###
