"""Agregar campos de firma al modelo CRT y campos de autenticacion al modelo Usuario

Revision ID: fc7680385d45
Revises: d518265a1a9a
Create Date: 2025-09-02 15:24:37.467438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc7680385d45'
down_revision = 'd518265a1a9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transportadoras', schema=None) as batch_op:
        batch_op.drop_column('codigo_interno')

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('ultimo_login', sa.DateTime(), nullable=True))
        batch_op.add_column(
            sa.Column('refresh_token', sa.String(length=512), nullable=True))
        batch_op.create_unique_constraint('uq_usuarios_email', ['email'])

    with op.batch_alter_table('crts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('firma_remitente',
                            sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('firma_transportador',
                            sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('firma_destinatario',
                            sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crts', schema=None) as batch_op:
        batch_op.drop_column('firma_destinatario')
        batch_op.drop_column('firma_transportador')
        batch_op.drop_column('firma_remitente')

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_constraint('uq_usuarios_email', type_='unique')
        batch_op.drop_column('refresh_token')
        batch_op.drop_column('ultimo_login')

    with op.batch_alter_table('transportadoras', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('codigo_interno', sa.VARCHAR(length=30), nullable=True))

    # ### end Alembic commands ###
